### PR TITLE
Add support for fastify

### PR DESCRIPTION
**Pull request by dbrixey**
Added auto instrumentation for fastify framework https://www.fastify.io/. Issue: https://github.com/signalfx/signalfx-nodejs-tracing/issues/74

### CODE REVIEW

**Comment by jtmalinowski** [comment]
Hi @dbrixey, could you tell me if you're a customer of SignalFx / Splunk Observability (can be over e-mail, see my profile)? In the meantime I'll check if we can accept external contributions.

**Comment by dbrixey** [comment]
Answer sent over email

**Comment by jtmalinowski** [comment]
Hi @dbrixey, I talked to the team and it looks like we require a CLA to be signed https://www.splunk.com/en_us/form/contributions.html before we can accept your code. Let me know if that works for you.

**Comment by dbrixey** [comment]
We'll need to check with our Legal team before signing the CLA. I'll follow up with them and get back to you.

In the meantime can you update https://github.com/signalfx/signalfx-nodejs-tracing/blob/master/CONTRIBUTING.md to include the requirement to sign the CLA?

**Comment by johanneslumpe** [comment]
@dbrixey Any update on this? We're also looking for fastify support. Can we expect this PR to be merged soon or are we better off forking?

**Comment by jtmalinowski** [comment]
Hi @johanneslumpe, I can't merge dbrixey's PR without the CLA. I emailed you about possible alternative solutions. If it doesn't pan out, I'll reimplement dbrixey's PR to work around licensing issues.

**Comment by johanneslumpe** [comment]
@jtmalinowski I was exactly curious about the CLA. Great to hear though that this will go forward either way. Would another solution be to just cherry pick required commits from datadog’s library? They do have fastify support.

**Comment by jtmalinowski** [comment]
Yeah, we'll most likely do that, if the alternative I emailed you about doesn't work out.

**Comment by romansavchenko** [comment]
Any updates on  this?

**Comment by jtmalinowski** [comment]
Because it is now official, I'd like to recommend <https://github.com/signalfx/splunk-otel-js> instead of `signalfx-nodejs-tracing`. It's more modern and it's designed to be more flexible. Fastify would be covered by <https://opentelemetry.io/registry/?s=fastify&component=&language=>, maybe you'll even be able to find more instrumentations you were missing. If you send me an email (address is in my profile), I can help with implementation. If you have reasons to keep using `signalfx-nodejs-tracing`, let me know and we'll move forward with this ticket.

**Pull request closed without merging**
